version: '3'

services:
  database:
    image: mysql
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - POSTGRES_PASSWORD=root
      - MYSQL_DATABASE= ofertacar
    restart: always
  redis:
    image: redis
    ports:
      - "3002:6379"